namespace MotorinApi.Dtos
{
    public class CreateHotWheelsCatalogDto
    {
        public string ProductLine { get; set; } = string.Empty;
        public string ModelName { get; set; } = string.Empty;
        public string ToyNumber { get; set; } = string.Empty;
        public string SeriesName { get; set; } = string.Empty;
        public string SeriesNumber { get; set; } = string.Empty;
        public string CastingName { get; set; } = string.Empty;
        public string ColorVariant { get; set; } = string.Empty;
        public string TampoDesign { get; set; } = string.Empty;
        public bool TreasureHunt { get; set; }
        public bool SuperTreasureHunt { get; set; }
        public int ManufactureYear { get; set; }
        public string ProductNumber { get; set; } = string.Empty;
        public string OfficialImageUrl { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        // CatalogId, CreatedAt, UpdatedAt excluded - generated by system
    }

    public class UpdateHotWheelsCatalogDto
    {
        public System.Guid CatalogId { get; set; }
        public string ProductLine { get; set; } = string.Empty;
        public string ModelName { get; set; } = string.Empty;
        public string ToyNumber { get; set; } = string.Empty;
        public string SeriesName { get; set; } = string.Empty;
        public string SeriesNumber { get; set; } = string.Empty;
        public string CastingName { get; set; } = string.Empty;
        public string ColorVariant { get; set; } = string.Empty;
        public string TampoDesign { get; set; } = string.Empty;
        public bool TreasureHunt { get; set; }
        public bool SuperTreasureHunt { get; set; }
        public int ManufactureYear { get; set; }
        public string ProductNumber { get; set; } = string.Empty;
        public string OfficialImageUrl { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
    }
}